import java.util.*;
import java.lang.*;
import java.io.*;

// The main method must be in a class named "Main".
class Main {
    public static void main(String[] args) {
        System.out.println("Hello world!");
        System.out.println("Primer punto");
        System.out.println("imprimir nombre y edad");
        String nom="Gloria Katerine Aguiar Cardona";
        int edad=16;
        System.out.println(nom);
        System.out.println(edad);

        System.out.println("Segundo punto");
        System.out.println("calcular la suma de dos numeros");
        int ka=5;
        int ri=8;
        System.out.println(ka+ri);

        System.out.println("Tercer punto");
        System.out.println("calcular la resta de dos numeros");
        int te=8;
        int go=4;
        System.out.println(te-go);

        System.out.println("Cuarto punto");
        System.out.println("calcular la multiplicacion de dos numeros");
        int we=8;
        int wo=8;
        System.out.println(we*wo);

        System.out.println("Quinto punto");
        System.out.println("calcular la division de dos numeros");
        int ta=10;
        int fo=2;
        System.out.println(ta/fo);

        System.out.println("Sexto punto");
        System.out.println("cuadrado de un numero");
        int ja=7;
        System.out.println(ja*ja);

        System.out.println("septimo punto");
        System.out.println("Convertir grados Celsius a Fahrenheit");
        int fo=45;
        int ca=9;
        int lo=5;
        int hi=32;                              
        System.out.println(fo*ca/lo+hi+"°");

        System.out.println("octavo punto");
        System.out.println("Calcular el perimetro de un rectangulo");
        int fi=17;
        int fa=11;
        System.out.println(fi+fa+fi+fa);

        System.out.println("Noveno punto");
        System.out.println("calcular el area de un circulo");
        int qu=3;
        double be=3.14;
        int ni=6;
        System.out.println(qu*be*ni);

        System.out.println("Decimo punto");
        System.out.println("convertir de años a dias");
        int fx=14;
        int fz=365;
        System.out.println(fx*fz);

        System.out.println("Onceavo punto");
        System.out.println("calcular el doble y el triple de un numero");
        int pp=89;
        System.out.println(pp+pp);
        System.out.println(pp+pp+pp);

        System.out.println("Doceavo punto");
        System.out.println("calcular de kilometros a metros centimetros");
        int km=9;
        int m=1000;
        int cm=100000;
        System.out.println(km*m);
        System.out.println(km*cm);
        
        System.out.println("Decimo tercer punto");
        System.out.println("calcular el area y el perimetro de un cuadrado");
        int am=8;
        System.out.println(am+am+am+am);
        System.out.println(am*am);

        System.out.println("Decimo cuarto punto");
        System.out.println("calcular el volumen de un cubo");
        int vo=7;
        System.out.println(vo*vo*vo);
        System.out.println("Decimo quinto punto");
        System.out.println("calcular el volumen de una esfera");
        int hy=4;
        int vi=3;
        double fu=3.14;
        int rad= 8*8*8;
        System.out.println(hy/vi*fu*rad);

        System.out.println("decimo sexto punto");
        System.out.println("sumar los primero 3 numeros naturales ");
        int xz=1;
        int qi=2;
        int sa=3;
        System.out.println(xz+qi+sa);

        System.out.println("Decimo septimo punto");
        System.out.println("calcular el descuento aplicado a una compra ");
        int hu=32700;
        double ce=0.10;
        System.out.println(hu*ce+"Este es el descuento.");

        System.out.println("Decimo octavo punto ");
        System.out.println("calcular la propina a dejar en un restaurante ");
        int ve=28000;
        double as=0.15;
        double au=ve*as;
        double jk=ve+au;
        System.out.println(au+"Total de la propina.");
        System.out.println(jk+"Valor completo.");
    }
}