System.out.println("Ejercicio 1 NOMBRE Y EDAD");
        
        String nombre= "Juan Camilo Bermudez Ortegon";
                
       System.out.println(nombre);
       
       System.out.println("  ");
       
       String edad="15 años";
       
       System.out.println(edad);
       
       
        System.out.println("  ");
       
      System.out.println("Ejercicio 2 SUMA DE DOS NÚMEROS");
       
      int m= 66;
      int n= 34;
      
      System.out.println("66+33:");
      System.out.println(m+n);
      
       System.out.println("  ");
       
      System.out.println("Ejercicio 3 RESTA DE DOS NÚMEROS");
      
       int a= 15;
       int b= 9; 
       
       System.out.println("15-9:");
       System.out.println(a-b);
       
       System.out.println("  ");
       
       
       System.out.println("Ejercicio 4 MULTIPLICACIÓN DE DOS NUMEROS");
       
       
       int x= 3;
       int y= 5;
       
       System.out.println("3*15:");
       System.out.println(x*y);
       
        System.out.println("  ");
        
         System.out.println("Ejercicio 5 DISIÓN DE DOS NÚMEROS");
         
         int p= 75;
         int q= 3;
         
         System.out.println("75/3:");
          System.out.println(p/q);
          
          
           System.out.println("  ");
        
         System.out.println("Ejercicio 6 CALCULAR EL CUADRADO DE UN NÚMERO");
         System.out.println("15*15");
         
         int o= 15;
                 
         System.out.println(o*o);
         
         System.out.println("  ");
        
         System.out.println("Ejercicio 7 CONVERSIÓN DE GRADOS CELSIUS A GRADOS FAHRENHEIT");
         
         int cº= 66;
          
         System.out.println("((66ºC*9/5)+32):ºf");
         System.out.println((cº*9/5)+32);
         
         System.out.println("  ");
        
         System.out.println("Ejercicio 8 CALCULAR EL PERIMETRO DE UN RECTANGULO");
         
         int lado1= 6;
         int lado2= 20;
         int lado3= 20;
         int lado4= 6;
         
         System.out.println("PERIMETRO:LADO 1 + LADO 2 + LADO 3 + LADO4");
         System.out.println(lado1 + lado2 + lado3 + lado4);
          
         
          System.out.println("  ");
        
         System.out.println("Ejercicio 9 CALCULAR EL ÁREA DE UN CIRCULO");
         System.out.println("PERIMETRO CIRCULO: π*`r²");
         
         double π= 3.141592653589793238;
         int r= 16;
         
         System.out.println("π*(16²)");
                
         System.out.println(π*(r*r));
         
          System.out.println("  ");
         
         System.out.println("Ejercicio 10 CONVERTIR AÑOS A DÍAS");
         
         int dia=1;
         int año= 365;
         
         System.out.println("1 día*365 días: 1 año");
         System.out.println(1*365);
         
         
           System.out.println("  ");
         
         System.out.println("Ejercicio 11 CALCULAR EL DOBLE Y EL TRIPLE DE UN NUMERO X");
         
         int z= 64;
         int X2= 2;
         int X3= 3;
        
         
         System.out.println("DOBLE DE z:z*2");
         System.out.println(z*X2);
         
         System.out.println(" ");
         
         System.out.println("TRIPLE DE z: z*3");
         System.out.println(z*X3);
         
          System.out.println("  ");
          
        System.out.println("Ejercicio 12 CONVERTIR Km a M y a Cm");
        
        int u= 5;
        int v= 5000;
        int w= 500000;
        
        System.out.println("5 Kilometros a Metros es igual a:");
        System.out.println (v);
        System.out.println("5 kilometros a centiemtros es igual a:");
        System.out.println(w);
        
        System.out.println("  ");
          
        System.out.println("Ejercicio 13 CALCULAR EL AREA Y PEIMETRO DE UN CUADRADO");
        System.out.println("AREA DE UN CUADRADO");
        
        int A= 7;
        int B= 7;
        int C= 7;
        int D= 7;
        
        System.out.println("A: lado X lado ");
        System.out.println(A*B);
        
        
        
        System.out.println("PERIMETRO DE UN CUADRADO");
        System.out.println("P: LADO + LADO + LADO + LADO");
        System.out.println(A+B+C+D);
        
        System.out.println("  ");
          
        System.out.println("Ejercicio 14 CALCULAR EL VOLUMEN DE UN CUBO");
        System.out.println("V: LADO*LADO*LADO");
        
        int E= 9;
               
        System.out.println(E*E*E);
        
         System.out.println("  ");
          
        System.out.println("Ejercicio 15 CALCULAR EL VOLUMEN DE UNA ESFERA");
        System.out.println("Volumen esfera:((4/3) * π * (r*r*r))");
        
        int R= 12;
        double f= 3.141592653589793238;
        
        System.out.println("(4/3)*π*(12*12*12)");
         System.out.println("(1.333333333)*π*(1728)");
          System.out.println(1.333333333*f*1728);
          
           System.out.println("  ");
          
        System.out.println("Ejercicio 16 SUMAR LOS TRES PRIMEROS NÚMEROS NATURALES");
        
        int N1= 1;
        int N2= 2;
        int N3= 3;
        
        System.out.println("1+2+3:");
        System.out.println(N1+N2+N3);
        
     System.out.println("  ");
          
        System.out.println("Ejercicio 17 CALCULAR EL DESCUENTO APLICADO A UNA COMPRA");  
        System.out.println("Celular Xiaomi Redmi note 14 de 800.000 COP");
      
         
      int COP= 800000;
      int descuento= 25;
      int PORCENTAJE= 100;
      
      System.out.println("20x800.000/100: descuento a ser aplicado");
      System.out.println(descuento*COP/PORCENTAJE);
      
     int pr= 200000;
     
     System.out.println("Precio inicial - descuento");
     System.out.println("800.000-200.000: Precio con el descuento aplicado");
     System.out.println(COP-pr);
     
       System.out.println("  ");
          
        System.out.println("Ejercicio 18 CALCULAR LA PROPINA A DEJAR EN UN RESTAURANTE");  
        System.out.println("El precio final de la comida es de 35.000 COP y se desea dejar una propina del 25%");
        
        
        int PRECIO= 35000;
        int DESCUENTO= 25;
        int porcentaje= 100;
        
        System.out.println("25x35.000/100");
        System.out.println(DESCUENTO*PRECIO/porcentaje);