public class KarolJimenez10A {

    public static void main(String[] args) {
      
  System.out.println("Primer Punto");
    System.out.println("Ingresar el nombre y la edad");
    String name= "Karol" ;
    int edad= 14;
    System.out.println(name) ;
    System.out.println(edad) ;
    
    System.out.println("Segundo punto");
    System.out.println("Calcular la suma de dos numeros");
    int numero1= 8;
    int numero2= 3;
    System.out.println(numero1+numero2);
    
    System.out.println("Tercer punto");
    System.out.println("Calcular la resta de dos numeros");
    int numero3=6;
    int numero4=4;
    System.out.println(numero3-numero4);
    
    System.out.println("Cuarto Punto");
    System.out.println("Calcular la mutiplicacion de dos numeros");
    int numero5= 7;
    int numero6= 9;  
    System.out.println(numero5*numero6);
    
    System.out.println("Quinto Punto");
    System.out.println("Calcular la division de dos numeros");
    int numero7=21;
    int numero8=3;
    System.out.println(numero7/numero8);
    
    int A=6 ;
    int B=6 ;
    int C=6*6 ;
    System.out.println("Sexto Punto");
    System.out.println("Cuadrado de un numero");
    System.out.println(+C);
  
   
    int Mi=28 ;
    int Ma=9;
    int Me=5;
    int Mo=32;
    int MoMo=Mi*Ma/Me+Mo;
    System.out.println("Septimo punto:");
    System.out.println("Calcular grados celcius a farenheit");
    System.out.println(+MoMo+"º");
    
    int mike=12 ;
    int once=18 ;
    int mikece=mike+once+mike+once;
    System.out.println("Octavo Punto :");
    System.out.println("Calcular perimetro de  un rectangulo");
    System.out.println(+mikece+"cm");
    
    int no=2 ;
    double j= 3.14 ;
    int ta=4 ;
    System.out.println("Noveno punto");
    System.out.println("Calcular area de un circulo");
    System.out.println(no*j*ta);
    
    int d=365 ;
    int g=4 ;
    int e=d*g;
    System.out.println("Decimo Punto:");
    System.out.println("Convertir años en dias");
    System.out.println(e+" Days");
    
    int da=9 ;
    int pu= 9*9 ;
    int co= 9*9*9 ;
    System.out.println("onceavo punto:");
    System.out.println("Calcular el doble y el triple de un numero ingresado");
    System.out.println("Onceavo punto ->Doble:"+pu);
    System.out.println("Onceavo punto ->Triple:"+co);   
        
    int km=45 ;
    int m= 1000 ;
    int cm= 100000 ;
    System.out.println("Doceavo punto");
    System.out.println("Calcular Kilometros a metros y centimetros");
    System.out.println("Doceavo punto->Km a M->" +km*m );    
    System.out.println("Doceavo punto->Km a Cm->" +km*cm );
    
    int La= 45;
    int pm= La+La+La+La ;
    int ar= La*La ;
    System.out.println("Decimo tercer punto");
    System.out.println("Calcular el área y perimetro de un cuadrado");
    System.out.println("Area->"+ar);
    System.out.println("Perimetro->"+pm);
    
    String unidad= "Cm al cubo" ;
    System.out.println("Decimo cuarto punto");
    System.out.println("Calcular el volumen de un cubo");
    System.out.println(La*La*La +unidad);
    
    int S= 3;
    int radio= 6;
    String uni= "Cm al cubo" ;
    System.out.println("Decimo Quinto punto");
    System.out.println("Calcular el volumen de una esfera");
    System.out.println((ta/S)*j*(radio*radio*radio) +uni);
   
    int Y= 1;
    int Q= 2;
    int U= 3;
    System.out.println("Decimo Sexto punto");
    System.out.println("Calcular la suma de los primeros tres numeros naturales");
    System.out.println(Y+Q+U);
   
    int ch = 200000; 
    int dc = 35;
    double descuento = ch * (dc / 100.0);
    double vf = ch - descuento;
    System.out.println("Decimo Séptimo punto");
    System.out.println("Calcular el descuento aplicado a una compra (precio y % de descuento)");
    System.out.println("Descuento aplicado: $" + descuento);
    System.out.println("Precio final: $" + vf);
   
   
    double cn = 67.500;
    double ps = 5.0; 
    double propina = cn * (ps / 100); 
    double total = cn + propina;
    System.out.println("Décimo Octavo punto");
    System.out.println("Calcular la propina a dejar en un restaurante (total y % deseado)");
    System.out.println("Valor de la cuenta: $" + cn);
    System.out.println("Propina: $" + propina);
    System.out.println("Total a pagar: $" + total);