       public class LauraCamilaGutierrez {

    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
    
    public static void main(String args) {
        //imprimir mi nombre y edad
    System.out.println("nombre y edad");
    System.out.println("laura Camila Gutierrez");
    System.out.println("16 años");

        
        //calcular la suma de dos numeros 
     System.out.println("suma de dos numeros");
        int a=54;
        int b=11;
        System.out.println(a+b);
        
        
        //calcular la resta dos numeros 
    System.out.println("resta dos numeros");
        int k=58;
        int j=8;
    System.out.println(k-j);


        
        //calcular la multiplicacion de dos numeros 
    System.out.println("multiplicacion de dos numeros");
        int y=87;
        int x=10;
    System.out.println(y*x);

        

        //calcular la division de dos numeros 
    System.out.println("division de dos numeros");
        int c=100;
        int p=2;
    System.out.println(c/p);

        

        //calcular el cuadrado de un numero
    System.out.println("perimetro de un numero");
        int z=50;
        int t= z*z;
    System.out.println(t);

      //convertir grados de celcius a  Fahrenheit
    System.out.println("grados de celcius a  Fahrenheit");
        double s=2;
        double r=2.8;
        double q=32;
    System.out.println(s*r+q);
        


        //Calcular el perímetro de un rectángulo.
    System.out.println("perimetro de un rectangulo");
        int lado=10;
        int formula= lado*4;
    System.out.println(formula);
        
    

        //calcular el area de un circulo 
    System.out.println("area de un circulo");
        double pi=4.22;
        double rd=6;
        double br=rd*rd;
    System.out.println(pi*br);


        
        //calcular años a dias 
    System.out.println("años a dias");
        int años=5;
        int dias=365;
       
    System.out.println(años*dias);
        
        

        //Calcular el doble y el triple de un número ingresado
    System.out.println("el doble un numero ingresado");
        int numero=15;
    System.out.println(numero+numero);
    System.out.println("el triple de un numero ingresado");
    System.out.println(numero+numero+numero);

        

        //Convertir kilómetros a metros y centímetros.
    System.out.println("kilometros a metros");
        int kilometros=5;
        int metros=1000;
    System.out.println(kilometros*metros);
    System.out.println("metros a centimetros");
        int metr=5000;
        int cen=100;
    System.out.println(metr*cen);


        //Calcular el área y el perímetro de un cuadrado
    System.out.println("area de un cuadrado");
        int ladoan=5;
        int ladola=5;
    System.out.println(ladoan*ladola);
    System.out.println("perimetro de un cuadrado");
    System.out.println(lado*4);


        //Calcular el volumen de un cubo
    System.out.println("volumen de un cubo");
        int volumen=8;
        int resu=volumen*volumen*volumen;
    System.out.println(resu);


        //Calcular el volumen de una esfera
    System.out.println("volumen de una esfera");
        double roro=4/3;
        double pii=3.14;
        double radi=12;
        double elev=radi*radi*radi;
    System.out.println(roro*pii*elev);


        //Sumar los tres primeros números naturales
    System.out.println("suma de los tres primeros numeros");
        int one=6;
        int two=8;
        int theere=10;
    System.out.println(one+two+theere);


        //Calcular el descuento aplicado a una compra precio y % de descuento
    System.out.println("descuento aplicado a una compra ,precio y % descuento");
         double precio=5000;
         double porcentaje=0.30;
    System.out.println(precio*porcentaje);
    System.out.println( "Insertar precio final");
    System.out.println(5000-precio*porcentaje);


        //Calcular la propina a dejar en un restaurante (total y % deseado)
    System.out.println("propina a dejar en un restaurante total y 5 deseado");
         double totalcuenta=500;
         double porcentajepropina=0.15 ;
    System.out.println(totalcuenta*porcentajepropina);
    System.out.println("Insertar valor final");
    System.out.println(500+totalcuenta*porcentajepropina);
        
        
        
    
    
    
    
    }
}

