public static void main(String[] args) {
        System.out.println("Imprimir tu nombre y edad.");
     
        System.out.println(" Ingrese nombre");
        String nombre="nahomy sofia castañeda cruz";
         System.out.println(" Nombre:" +nombre);
        System.out.println( " Ingrese edad");
        int edad=15;
        System.out.println(" Edad:" + edad);
        
        System.out.println("Calcular la suma de dos numeros");
        int h=6;
        int m=8;
        System.out.println(h+m);
        
        System.out.println("Restar dos numeros");
        long p=15;
        long d=9;
        System.out.println(p-d);
        
        System.out.println("Multiplicar dos numeros");
        byte a=56;
        byte b=9;
        System.out.println(a*b);
        
          System.out.println("Dividir dos numeros");
          int y=78;
          int l=13;
          System.out.println(y/l);
          
          System.out.println("Calcular el cuadrado de un numero.");
          double u=2.6;
          double si=(u*u);
          System.out.println(si);
          
          System.out.println("Grados Celsius a Fahrenheit.");
          int ma=45;
          int mo=9;
          int mu=5;
          int mi=32;
          System.out.println(ma*mo/mu+mi);
          
          System.out.println("perimetro de un rectangulo");
          byte w=54;
          byte x=12;
          byte sa=54;
          byte il=12;
          System.out.println(w+x+sa+il);
          
          System.out.println( "area de un circulo.");
          double pi=3.14;
          int ra= 14;
          System.out.println(pi*(ra*ra));
          
          System.out.println("Convertir años a dias");
          int añ=26;
          int di=365;
          int ya=1;
          System.out.println(añ*di/ya);
          
          
          System.out.println("el doble y el triple de un número ingresado");
          System.out.println("Ingresa el doble");
         int f=24;
         System.out.println(f+f);
          System.out.println("Ingresa el triple");
          System.out.println(f+f+f);
          
          System.out.println(" kilómetros a metros y centímetros.");
                    System.out.println("kilometros a metros");
          int ki=59;
          int me=1000;
          System.out.println(ki*me);
          System.out.println("metros a centimetros");
          int met=59000;
          int ce=100;
          System.out.println(met*ce);
          
          System.out.println("area y el perimetro de un cuadrado");
           
           System.out.println("Ingresa el area");
           
           double lado=4.3;
           System.out.println(lado*lado);
           
            System.out.println("Ingresa el perimetro");
            byte perimetro=18;
            byte exponente=4;
            System.out.println(perimetro*exponente);
            
             System.out.println("volumen de un cubo");  
             
             int volumen=20;
             int elevado=3;
             System.out.println(volumen*elevado);
             
             System.out.println("volumen de una esfera");
             
             byte de=4/3;
             double pa=3.14;
             byte va=12;
             byte ele=3;
             System.out.println(de*pa*va*ele);
             
             System.out.println("Sumar los tres primeros numeros naturales");
          int ko=1;
          int ka=2;
          int ke=3;
          System.out.println(ko+ka+ke);
          
          System.out.println("Calcular el descuento aplicado a una compra (precio y % de descuento).");
          
          int precio=200;
          double porcentaje=0.30;
          System.out.println(precio*porcentaje);
          System.out.println( "Insertar precio final");
          System.out.println(200-precio*porcentaje);
          
          System.out.println("Calcular la propina a dejar en un restaurante (total y % deseado)");
          int totalcuenta=45000;
          double porcentajepropina=0.15 ;
          System.out.println(totalcuenta*porcentajepropina);
          System.out.println("Insertar valor final");
          System.out.println(45000+totalcuenta*porcentajepropina);
